# Generated by Django 4.0.3 on 2022-03-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_reviewed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Fantasy', 'Fantasy'), ('Education', 'Education'), ('Autobiography', 'Autobiography'), ('Criminal', 'Criminal'), ('Romantic', 'Romantic'), ('Science Fiction', 'Science Fiction'), ('Comic Book', 'Comic Book'), ('Classic', 'Classic'), ('Horror', 'Horror'), ('Not specified', 'Not specified')], default='Not specified', max_length=15),
            preserve_default=False,
        ),
    ]
