# Generated by Django 4.0.3 on 2022-03-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_approved',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved')], default='Waiting for Approval', max_length=50, verbose_name='Approve'),
        ),
    ]
