# Generated by Django 4.0.3 on 2022-03-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_book_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_approved',
            field=models.CharField(choices=[('APPROVED', 'APPROVED'), ('NOT_APPROVED', 'NOT_APPROVED')], default='Waiting for approval', max_length=12, verbose_name='Approve'),
        ),
    ]
