# Generated by Django 4.0.3 on 2022-04-11 18:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('picture', models.ImageField(blank=True, default='user_images/default_profile_picture.jpg', null=True, upload_to='user_images/')),
                ('first_name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(1)])),
                ('last_name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(1)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
