# Generated by Django 4.0.3 on 2022-04-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_alter_authuser_last_name_alter_authuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='first_name',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
