# Generated by Django 4.0.3 on 2022-03-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_alter_authuser_first_name_alter_authuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='default_profile_picture.jpg', null=True, upload_to='user_images/'),
        ),
    ]
