# Generated by Django 4.0.3 on 2022-04-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0003_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='user_images/default_profile_picture.jpg', null=True, upload_to='user_images/'),
        ),
    ]
