# Generated by Django 4.0.3 on 2022-04-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_approved',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved'), ('Waiting for approval', 'Waiting for approval')], default='Waiting for approval', max_length=20, verbose_name='Approve'),
        ),
    ]
