# Generated by Django 4.0.3 on 2022-04-02 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0003_alter_profile_picture'),
        ('review', '0002_rename_book_comment_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commented_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth_user.profile'),
            preserve_default=False,
        ),
    ]
