# Generated by Django 4.0.3 on 2022-04-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_alter_review_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
